[package]
name = "frameg"
version = "0.1.0"
edition = "2021"

[lib]
name = "frameg"
path = "src/lib.rs"

[dependencies]
iced = "0.13.1"
ron = "0.8.1"
serde = { version = "1.0.210", features = ["derive"] }
